name: Water Temperature Scraping and RSS Feed Generation

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # Update to use main branch

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Update to use Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedgen

      - name: Run scraping script
        run: python watertemp.py

      - name: Generate RSS feed
        run: python rss_feed_generation.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add temperature.db temperature_feed.xml
          git commit -m 'Update water temperature data and RSS feed [skip ci]'
          git push
